<?php
// $Id;

/**
 * @file
 *
 * Provide a block that displays the children of the active menu item.
 *
 * TODO:
 * Should allow you to set the menu depth at which to start looking for children per block.
 * Need some way to delete blocks.
 */
 
/**
 * Implementation of hook_menu().
 */
function secondary_nav_block_menu() {
  $items = array();
  $items['admin/build/block/add-secondary-nav-block'] = array(
    'title' => 'Add secondary nav block',
    'description' => 'Add a new secondary navigation block and configure the associated menu.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secondary_nav_block_add'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/build/block/delete-secondary-nav-block/%'] = array(
    'title' => 'Delete block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secondary_nav_block_delete_confirm', 4),
    'access arguments' => array('administer blocks'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_block().
 */
function secondary_nav_block_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $results = db_query('SELECT * FROM {secondary_nav_block_blocks} ORDER BY bid');
    $blocks = array();
    while ($block = db_fetch_object($results)) {
      $blocks[$block->bid] = array(
        'info' => t('Secondary Navigation Block [@menu - @start_level]', array('@menu' => $block->menu, '@start_level' => $block->start_level)),
        'weight' => 0,
        'status' => 0,
        'region' => NULL, 
      );
    }
    return $blocks;
    
  }
  else if ($op == 'view') {
    return _secondary_nav_block_block_content($delta);
  }
}

function secondary_nav_block_form_alter(&$form, $form_state, $form_id) {
  // Add delete links for each of our blocks.
  if ($form_id == 'block_admin_display_form') {
    $results = db_query('SELECT * FROM {secondary_nav_block_blocks}');
    while ($block = db_fetch_object($results)) {
      if ($form['secondary_nav_block_'. $block->bid]) {
        $form['secondary_nav_block_'. $block->bid]['delete'] = array(
          '#value' => l('delete', 'admin/build/block/delete-secondary-nav-block/'. $block->bid),
        );
      }
    }
  }
}

/**
 * Menu callback, display form for adding a new secondary_nav_block.
 */
function secondary_nav_block_add() {
  $form = array();

  $menus = menu_get_menus();
  $form['description'] = array(
    '#type' => 'markup',
    '#value' => '<p>Choose a menu from the list below that this block should act on. When a top level menu item from the selected menu is active this block will display all children of that item.</p>',
  );
  $form['use_menu'] = array(
    '#title' => t('Menu'),
    '#type' => 'select',
    '#options' => $menus,
    '#required' => TRUE,
  );
  $form['start_level'] = array(
    '#title' => t('Start Depth'),
    '#type' => 'select',
    '#options' => array('', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
    '#description' => t('Depth within the selected menu at which secondary navigation starts.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create block'),
  );
  
  return $form;
}

/**
 * Submit callback for secondary_nav_block_add.
 */
function secondary_nav_block_add_submit($form, &$form_state) {
  $secondary_nav_block = array(
    'menu' => $form_state['values']['use_menu'],
    'start_level' => $form_state['values']['start_level'],
  );
  drupal_write_record('secondary_nav_block_blocks', $secondary_nav_block);
  drupal_set_message('Your block has been created, please configure it below.');
  $form_state['redirect'] = 'admin/build/block';
}

/**
 * Menu callback, display form to confirm users intent to delete a block.
 */
function secondary_nav_block_delete_confirm(&$form_state, $bid) {
  $form['bid'] = array(
    '#type' => 'value',
    '#value' => $bid
  );
  return confirm_form($form,
    t('Are you sure you want to delete this block?'),
    'admin/build/block',
    t('This action cannot be undone.'),
    t('Delete'),
    t('Cancel')
  );    
}

/**
 * Submit callback for secondary_nav_block_delete_confirm.
 * Delete the specified block if confirmed.
 */
function secondary_nav_block_delete_confirm_submit($form, &$form_state) {
  if ($form_state['values']['confirm']) {
    db_query('DELETE FROM {secondary_nav_block_blocks} WHERE bid=%d', $form_state['values']['bid']);
    drupal_set_message('Your block has been deleted');
  }
  $form_state['redirect'] = 'admin/build/block';
}

/**
 * Create a secondary navigation menu
 *
 * @return string
 */
function _secondary_nav_block_block_content($delta){
  $block_info = db_fetch_object(db_query('SELECT * FROM {secondary_nav_block_blocks} WHERE bid=%d', $delta));

  $output = '';
  $level = ($block_info->start_level <= 1) ? 1 : $block_info->start_level;

  // Get the menu hierarchy for the current page.
  $tree = menu_tree_page_data($block_info->menu);

  // Go down the active trail until the right level is reached.
  while ($level-- > 0 && $tree) {
    // Loop through the current level's items until we find one that is in trail.
    while ($item = array_shift($tree)) {
      if ($item['link']['in_active_trail']) {
        // If the item is in the active trail, we continue in the subtree.
        $parent_title = $item['link']['title'];
        $tree = empty($item['below']) ? array() : $item['below'];
        break;
      }
    }
  }

  if ($tree) {
    $output = menu_tree_output($tree);
    return array('subject' => $parent_title, 'content' => $output);
  }

  return NULL;
}